### PR TITLE
build: bump dependencies

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

Yesterday the dependent bot submitted a PR #483 to bump vite. A good reminder we should stay up-to-date with the dev dependencies

# Changes

- Update dev dependencies except eslint and typescript for compatibility reason and marked because there are some breaking changes

### CODE REVIEW

**Comment by dskloetd** [comment]
Can you update the screenshots?

**Comment by peterpeterparker** [comment]
Ah yeah sure. Did not noticed the CI ended in error.

**Comment by peterpeterparker** [comment]
Snapshots updated. Looks ok, they probably diverge on few pixels.

**Review by dskloetd — APPROVED** [review]
Looks like the font changed. Weird, but ok.

**Pull request merged**
