### PR TITLE
Key value info align icon right

### PR DESCRIPTION
**Pull request by mstrasinskis**
# Motivation

Add property `alignIconRight` to align info icons to the right

# Changes

- alignIconRight
- align value text right to improve long text alignment (mobile screenshot)

# Screenshots

## Mobile
image

## Desktop
image

### CODE REVIEW

**Comment by peterpeterparker** [comment]
What happens if the value is for example a copy button? Is that expected?

Text | Value button button

**Review by lmuntaner — APPROVED** [review]
LGTM!

If the user of the component puts an icon there, it's up to them to find a better solution, no?

The library can't fix all the misuses of the components.

**Comment by peterpeterparker** [comment]
Well this issue cannot happen currently with this or any other component of the library no?

**Comment by peterpeterparker** [comment]
Discussed offline with @mstrasinskis. Don't mind me.

**Pull request merged**
