### PR TITLE
feat: add and adjust prop size for icons

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

Whenever possible, it would be ideal to provide the prop `size` for the icons. Most of them were already defaulting to the initial value of `20px`.

### CODE REVIEW

**Review by mstrasinskis — COMMENTED** [review]
Looks good, but there is something broken according to the screenshot:
image

Or fixed :)

**Comment by mstrasinskis** [comment]
@AntonioVentilii-DFINITY , do you know what the changes are in the first screenshot?

**Comment by AntonioVentilii-DFINITY** [comment]
@mstrasinskis I am not really sure to be honest... I used a image comparison tool that pointed out the parentesis in the text under "Your ICP Wallet", but it doesn't make much sense...

**Comment by mstrasinskis** [comment]
> @mstrasinskis I am not really sure to be honest... I used a image comparison tool that pointed out the parentesis in the text under "Your ICP Wallet", but it doesn't make much sense...
> 
> theoretically, the user icon at the top-right changed too, but it shouldn't really, since it is the same size...

@AntonioVentilii-DFINITY, have you tried reverting the changes in this screenshot? Will the test pass?

**Review by mstrasinskis — APPROVED** [review]
LGTM, it's just weird that the first screenshot was updated, but nothing critical.

**Comment by dskloetd** [comment]
FYI: https://github.com/dfinity/gix-components/pull/490

**Pull request merged**
