### PR TITLE
Remove box-shadow on Popover

### PR DESCRIPTION
**Pull request by dskloetd**
# Motivation

Artem asked me to remove the box-shadow on the Popover.
Until recently the Popover always had a visible dark backdrop where the box-shadow wasn't really visible anyway so this should only make a difference for the new cases where we hide the backdrop.

# Changes

Remove `box-shadow` style on `Popover`.

# Screenshots

Before:
image

After:
image

### CODE REVIEW

**Review by mstrasinskis — APPROVED** [review]
Thanks!

**Comment by peterpeterparker** [comment]
Did Artem confirm that he also want to remove it in Oisy?

**Comment by peterpeterparker** [comment]
Additional question, did Artem expliticely said he want to keep the box-shadow on modals or should it be removed too?

**Comment by peterpeterparker** [comment]
@dskloetd already merged? Did you noticed my questions?

**Pull request merged**
