### PR TITLE
delete stopPropagation on onClick and onKeypress in Popover

### PR DESCRIPTION
**Pull request by coskucinkilic**
# Motivation

Make LinkToCanister component function as expected in nnsDapp

# Changes

stopPropagation on onClick and onKeypress in Popover are deleted

# Screenshots

### CODE REVIEW

**Comment by peterpeterparker** [comment]
I'm not sure about this change. Doesn't it imply that, for example, if I click and select text displayed in a popover, the popover will close itself which we most likely not want?

Also, can you explain why this change was made? What issue does it resolve?

**Comment by dskloetd** [comment]
@peterpeterparker it appears that this component originates from papyrs and the `stopPropagation` was added by you in 
https://github.com/papyrs/papyrs/commit/c80cf288d479d82461e583b8727195df5f200e89

It doesn't seem to have much explanation of why. Do you remember why you added it?

The problem @coskucinkilic is trying to solve is that if you click on an in-app link in a Popover, it doesn't result in an in-app navigation as with other in-app links but results in a complete page reload.

**Comment by peterpeterparker** [comment]
@dskloetd as I said in my comment, I got the feeling that if you remove the stop propagation, it may results in the popover closing it self for example if the user clicks or select text in the popover. Question mark, so if it's not the case for sure it's fine.

**Comment by dskloetd** [comment]
That would make sense if the backdrop were a parent of the element on which `stopPropagation` is removed. But it's not.

@coskucinkilic can you deploy a canister with this change to you DevEnv so we can all try and see if it causes any problems?

**Comment by peterpeterparker** [comment]
> can you deploy a canister

Unrelated to the PR but to the comment: If the Juno DAO succeeds, one of the features hidden in the roadmap goal 'Better CI/GitHub integration' is the ability to easily deploy staging or other dev versions from PRs, similar to what's done on Vercel, for example.

**Comment by coskucinkilic** [comment]
I have deployed changes in this PR and [this PR in nnsDapp](https://github.com/dfinity/nns-dapp/pull/5567) to devenv, feel free to review in[ this devenv](https://qsgjb-riaaa-aaaaa-aaaga-cai.cosku-ingress.devenv.dfinity.network/).

**Comment by dskloetd** [comment]
Thanks. I've tested
1. Clicking on the popover does not close it.
2. Clicking on the copy button s in the popover does not close it.
3. Clicking on Manager Internet Identity opens Internet Identity in a separate tab and does not close the popover
4. Clicking Settings does close the popover and navigates to settings
5. Clicking Canisters closes the popover and navigates to canisters
This all seems correct.
@peterpeterparker what do you think?

**Comment by peterpeterparker** [comment]
Sounds good. Thanks for the test, appreciated! Let's go then.

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
