### PR TITLE
Chore: Fix vulnerability issues

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

Fix security issues.

# Changes

Only automatic changes after running `npm audit fix`

# Screenshots

No changes.

### CODE REVIEW

**Comment by lmuntaner** [comment]
@peterpeterparker please review

They were brought up by a security issue: https://dfinity.atlassian.net/browse/SCAVM-631

**Comment by peterpeterparker** [comment]
Have you try to bump vitest to see if it solves the issue? We are behind, last release is v0.34.6

`npm rm vitest && npm i vitest -D`?

**Comment by lmuntaner** [comment]
> Have you try to bump vitest to see if it solves the issue? We are behind, last release is v0.34.6
> 
> `npm rm vitest && npm i vitest -D`?

Yes, the issue seems fixed, but the test don't run anymore:

```
Error: Failed to resolve entry for package "@sveltejs/package". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@sveltejs/package" package
```

And I found this issue in vitest repo: https://github.com/vitest-dev/vitest/issues/4194

I felt to first manage the security issue and we can consider upgrading vitest in another moment. WDYT?

**Comment by peterpeterparker** [comment]
Gotcha

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
